name: Sachin Portfolio CICD

on:
  push:
    branches:
      - main
  workflow_dispatch: 

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # ---------------------------------------------------------
  # STAGE 1: Build (Freeze Flask Application)
  # ---------------------------------------------------------
  build:
    name: BUILD
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Print Logs
        run: echo "Sachin Job Working"